sudo: required
services:
  - docker

before_install:
  - docker build -t alpanachaphalkar/docker-react -f Dockerfile.dev .

script:
  - docker run alpanachaphalkar/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: docker-travis-aws
  env: DockerTravisAws-env
  bucket_name: elasticbeanstalk-us-east-1-120026532180
  bucket_path: docker-travis-aws
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"