sudo: required
services:
  - docker

before_install:
  - docker build -t alpanachaphalkar/docker-react -f Dockerfile.dev .

script:
  - docker run alpanachaphalkar/docker-react npm run test -- --coverage